### ISSUE TITLE
Add /cvmfs/cms-opendata-conddb.cern.ch to /etc/cvmfs/default.local

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/play-with-docker.github.io#2]
`/cvmfs/cms-opendata-conddb.cern.ch` needs to be added in order to be able to use the same commands as in the docker and cmssw pre-exercises:
- https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/05-validation/index.html
- https://cms-opendata-workshop.github.io/workshop-lesson-cmssw/05_configuration/index.html

**Comment by katilp** [comment]
And `cms-bril.cern.ch` as well for `brilcalc` to work

**Comment by clelange** [comment]
@katilp should be fixed, reopen if not.
